module.exports = {
  NZLX: { name: "Alexandra", area: "CY" },
  NZAR: { name: "Ardmore", area: "TA" },
  NZBC: { name: "ASB Bank Centre", area: "TA" },
  NZAS: { name: "Ashburton", area: "PL" },
  NZAA: { name: "Auckland", area: "TA" },
  NZAW: { name: "Auckland Harbour", area: "TA" },
  NZJL: { name: "Auckland Hospital", area: "TA" },
  NZAL: { name: "Avalon", area: "ST" },
  NZBA: { name: "Balclutha", area: "GE" },
  NZJI: { name: "Bay of Islands Hospital", area: "FN" },
  NZBW: { name: "Burwood Hospital", area: "PL" },
  NZCG: { name: "Centennial Park", area: "CP" },
  NZCB: { name: "Centre Bush", area: "GE" },
  NZCI: { name: "Chatham Islands/Tuuta", area: "PL" },
  NZCH: { name: "Christchurch", area: "PL" },
  NZJC: { name: "Christchurch Hospital", area: "PL" },
  NZJJ: { name: "Christchurch Hospital Hagley", area: "PL" },
  NZCL: { name: "Cloudy Bay", area: "ST" },
  NZCX: { name: "Coromandel", area: "TA" },
  NZCW: { name: "Cromwell", area: "CY" },
  NZCS: { name: "Cromwell Racecourse", area: "CY" },
  NZDV: { name: "Dannevirke", area: "DV" },
  NZDA: { name: "Dargaville", area: "FN" },
  NZJE: { name: "Dargaville Hospital", area: "FN" },
  NZDN: { name: "Dunedin", area: "GE" },
  NZDC: { name: "Dunedin City", area: "GE" },
  NZDH: { name: "Dunedin Hospital", area: "GE" },
  NZDU: { name: "Dunstan Hospital", area: "CY" },
  NZEV: { name: "Eves Valley", area: "TN" },
  NZFI: { name: "Feilding", area: "SA" },
  NZFG: { name: "Fern Gully", area: "GE" },
  NZFE: { name: "Fernside Fields", area: "PL" },
  NZFL: { name: "Flat Hills", area: "SA" },
  NZFT: { name: "Flat Point", area: "DV" },
  NZFF: { name: "Forest Field", area: "PL" },
  NZFH: { name: "Fox", area: "WW" },
  NZFO: { name: "Fox Glacier", area: "WW" },
  NZFP: { name: "Foxpine", area: "SA" },
  NZFJ: { name: "Franz Josef", area: "WW" },
  NZGA: { name: "Galatea", area: "ED" },
  NZGS: { name: "Gisborne", area: "MH" },
  NZJG: { name: "Gisborne Hospital", area: "MH" },
  NZGH: { name: "Glacier Country", area: "WW" },
  NZGY: { name: "Glenorchy", area: "CY" },
  NZGT: { name: "Glentanner", area: "AL" },
  NZGC: { name: "Gore", area: "GE" },
  NZGB: { name: "Great Barrier", area: "TA" },
  NZGR: { name: "Great Mercury Island", area: "ED" },
  NZGM: { name: "Greymouth", area: "WW" },
  NZHT: { name: "Haast", area: "WW" },
  NZHN: { name: "Hamilton", area: "TK" },
  NZHS: { name: "Hastings", area: "DV" },
  NZJH: { name: "Hastings Hospital", area: "DV" },
  NZHA: { name: "Hawera", area: "SA" },
  NZHB: { name: "Helena Bay", area: "FN" },
  NZHK: { name: "Hokitika", area: "WW" },
  NZNV: { name: "Invercargill", area: "GE" },
  NZKO: { name: "Kaikohe", area: "FN" },
  NZKI: { name: "Kaikoura", area: "KA" },
  NZKJ: { name: "Kaikoura Beachfront", area: "KA" },
  NZKF: { name: "Kaipara Flats", area: "TA" },
  NZKT: { name: "Kaitaia", area: "FN" },
  NZJK: { name: "Kaitaia Hospital", area: "FN" },
  NZKM: { name: "Karamea", area: "TN" },
  NZWE: { name: "Kauaroa Bay", area: "TA" },
  NZKH: { name: "Kenepuru Hospital", area: "ST" },
  NZKK: { name: "Kerikeri/Bay of Islands", area: "FN" },
  NZKP: { name: "Koputaroa", area: "SA" },
  NZKY: { name: "Kowhai", area: "DV" },
  NZKU: { name: "Kupe", area: "SA" },
  NZHP: { name: "Lake Haupiri", area: "WW" },
  NZLE: { name: "Lake Station/Nelson Lakes", area: "TN" },
  NZLA: { name: "Loburn Abbey", area: "PL" },
  NZMX: { name: "Maari", area: "SA" },
  NZMW: { name: "Makarora", area: "CY" },
  NZOG: { name: "Makarora Heliport", area: "CY" },
  NZVL: { name: "Mandeville", area: "GE" },
  NZMG: { name: "Mangonui", area: "FN" },
  NZSO: { name: "Marlborough Sounds", area: "ST" },
  NZMJ: { name: "Martins Bay", area: "FD" },
  NZMS: { name: "Masterton", area: "DV" },
  NZMA: { name: "Matamata", area: "TK" },
  NZUA: { name: "Maui A", area: "SA" },
  NZUB: { name: "Maui B", area: "SA" },
  NZMB: { name: "Mechanics Bay", area: "TA" },
  NZME: { name: "Mercer", area: "TA" },
  NZML: { name: "Mid Waiho Loop", area: "WW" },
  NZMF: { name: "Milford Sound", area: "FD" },
  NZMK: { name: "Motueka", area: "TN" },
  NZKD: { name: "Motu Kaikoura Island", area: "TA" },
  NZMC: { name: "Mount Cook", area: "AL" },
  NZMR: { name: "Murchison", area: "TN" },
  NZUR: { name: "Murchison Hospital", area: "TN" },
  NZNR: { name: "Napier", area: "DV" },
  NZNS: { name: "Nelson", area: "TN" },
  NZNH: { name: "Nelson Hospital", area: "TN" },
  NZNP: { name: "New Plymouth", area: "TK" },
  NZNF: { name: "Norfolk", area: "TK" },
  NZNE: { name: "North Shore", area: "TA" },
  NZJN: { name: "North Shore Hospital", area: "TA" },
  NZOU: { name: "Oamaru", area: "PL" },
  NZOR: { name: "Oamaru Hospital", area: "PL" },
  NZOB: { name: "Ocean Beach", area: "GE" },
  NZOH: { name: "Ohakea (MIL)", area: "SA" },
  NZOX: { name: "Okiwi Station", area: "TA" },
  NZOF: { name: "Omaha Flats", area: "TA" },
  NZOM: { name: "Omaka", area: "ST" },
  NZOA: { name: "Omarama", area: "AL" },
  NZOP: { name: "Opotiki", area: "ED" },
  NZOT: { name: "Otaki", area: "ST" },
  NZPA: { name: "Paihia", area: "FN" },
  NZPM: { name: "Palmerston North", area: "SA" },
  NZJM: { name: "Palmerston North Hospital", area: "SA" },
  NZPW: { name: "Papawai", area: "DV" },
  NZPI: { name: "Parakai", area: "TA" },
  NZPP: { name: "Paraparaumu", area: "ST" },
  NZUN: { name: "Pauanui Beach", area: "ED" },
  NZPN: { name: "Picton", area: "ST" },
  NZPK: { name: "Pikes Point", area: "TA" },
  NZPO: { name: "Porangahau", area: "DV" },
  NZPH: { name: "Pudding Hill", area: "PL" },
  NZUK: { name: "Pukaki", area: "AL" },
  NZPU: { name: "Pukekohe", area: "TA" },
  NZQN: { name: "Queenstown", area: "CY" },
  NZQW: { name: "Queens Wharf", area: "ST" },
  NZRA: { name: "Raglan", area: "TK" },
  NZRT: { name: "Rangiora", area: "PL" },
  NZRK: { name: "Rangitaiki", area: "CP" },
  NZRI: { name: "Rangitata Island", area: "PL" },
  NZJW: { name: "Rawene Hospital", area: "FN" },
  NZRO: { name: "Rotorua", area: "ED" },
  NZJO: { name: "Rotorua Hospital", area: "ED" },
  NZLF: { name: "Rotorua Lakefront", area: "ED" },
  NZRL: { name: "Rotorua Lakes", area: "ED" },
  NZRX: { name: "Roxburgh", area: "CY" },
  NZRW: { name: "Ruawai", area: "FN" },
  NZRC: { name: "Ryans Creek", area: "GE" },
  NZSH: { name: "Skyline Helipad", area: "CY" },
  NZJS: { name: "Southland – Kew Hospital", area: "GE" },
  NZSF: { name: "Springfield", area: "PL" },
  NZSL: { name: "Springhill", area: "TA" },
  NZSD: { name: "Stratford", area: "SA" },
  NZAH: { name: "Taharoa Iron Sands", area: "TK" },
  NZTI: { name: "Taieri", area: "GE" },
  NZVR: { name: "Taihape", area: "SA" },
  NZTK: { name: "Takaka", area: "TN" },
  NZJQ: { name: "Taranaki Base Hospital", area: "TK" },
  NZTM: { name: "Taumarunui", area: "TK" },
  NZJT: { name: "Taumarunui Hospital", area: "TK" },
  NZAP: { name: "Taupo", area: "CP" },
  NZJZ: { name: "Taupo Hospital", area: "CP" },
  NZLT: { name: "Taupo Water", area: "CP" },
  NZTG: { name: "Tauranga", area: "ED" },
  NZJA: { name: "Tauranga Hospital", area: "ED" },
  NZMO: { name: "Te Anau/Manapouri", area: "FD" },
  NZTL: { name: "Tekapo", area: "AL" },
  NZTP: { name: "Tekapo/Mackenzie", area: "AL" },
  NZTE: { name: "Te Kowhai", area: "TK" },
  NZTT: { name: "Te Kuiti", area: "TK" },
  NZTQ: { name: "Te Kuiti Hospital", area: "TK" },
  NZJP: { name: "Te Puia Springs Hospital", area: "MH" },
  NZTH: { name: "Thames", area: "TA" },
  NZJD: { name: "Thames Hospital", area: "TA" },
  NZTU: { name: "Timaru", area: "PL" },
  NZTO: { name: "Tokoroa", area: "ED" },
  NZJX: { name: "Tokoroa Hospital", area: "ED" },
  NZUI: { name: "Tui", area: "SA" },
  NZTN: { name: "Turangi", area: "CP" },
  NZKE: { name: "Waiheke", area: "TA" },
  NZWV: { name: "Waihi Beach", area: "ED" },
  NZHH: { name: "Waikato Hospital", area: "TK" },
  NZWM: { name: "Waimate", area: "PL" },
  NZYP: { name: "Waipukurau", area: "DV" },
  NZMH: { name: "Wairarapa Hospital", area: "DV" },
  NZJB: { name: "Wairau Hospital", area: "ST" },
  NZWO: { name: "Wairoa", area: "MH" },
  NZJY: { name: "Wairoa Hospital", area: "MH" },
  NZWF: { name: "Wanaka", area: "CY" },
  NZWN: { name: "Wellington", area: "ST" },
  NZWH: { name: "Wellington Hospital", area: "ST" },
  NZWJ: { name: "Wellsford", area: "TA" },
  NZWL: { name: "West Melton", area: "PL" },
  NZWS: { name: "Westport", area: "WW" },
  NZWK: { name: "Whakatane", area: "ED" },
  NZJF: { name: "Whakatane Hospital", area: "ED" },
  NZWG: { name: "Whangamata", area: "ED" },
  NZWU: { name: "Whanganui", area: "SA" },
  NZJU: { name: "Whanganui Hospital", area: "SA" },
  NZWR: { name: "Whangarei", area: "FN" },
  NZJR: { name: "Whangarei Hospital", area: "FN" },
  NZES: { name: "Wharepapa South", area: "TK" },
  NZWP: { name: "Whenuapai (MIL)", area: "TA" },
  NZWT: { name: "Whitianga", area: "ED" },
  NZWB: { name: "Woodbourne", area: "ST" },
  NZWY: { name: "Wyndale", area: "PL" }
};
