module.exports = {
  NZLX: "Alexandra",
  NZAR: "Ardmore",
  NZBC: "ASB Bank Centre",
  NZAS: "Ashburton",
  NZAA: "Auckland",
  NZAW: "Auckland Harbour",
  NZJL: "Auckland Hospital",
  NZAL: "Avalon",
  NZBA: "Balclutha",
  NZJI: "Bay of Islands Hospital",
  NZBW: "Burwood Hospital",
  NZCG: "Centennial Park",
  NZCB: "Centre Bush",
  NZCI: "Chatham Islands/Tuuta",
  NZCH: "Christchurch",
  NZJC: "Christchurch Hospital",
  NZJJ: "Hagley",
  NZCL: "Cloudy Bay",
  NZCX: "Coromandel",
  NZCW: "Cromwell",
  NZCS: "Cromwell Racecourse",
  NZDV: "Dannevirke",
  NZDA: "Dargaville",
  NZJE: "Dargaville Hospital",
  NZDN: "Dunedin",
  NZDC: "Dunedin City",
  NZDH: "Dunedin Hospital",
  NZDU: "Dunstan Hospital",
  NZEV: "Eves Valley",
  NZFI: "Feilding",
  NZFG: "Fern Gully",
  NZFE: "Fernside Fields",
  NZFL: "Flat Hills",
  NZFT: "Flat Point",
  NZFF: "Forest Field",
  NZFH: "Fox",
  NZFO: "Fox Glacier",
  NZFP: "Foxpine",
  NZFJ: "Franz Josef",
  NZGA: "Galatea",
  NZGS: "Gisborne",
  NZJG: "Gisborne Hospital",
  NZGH: "Glacier Country",
  NZGY: "Glenorchy",
  NZGT: "Glentanner",
  NZGC: "Gore",
  NZGB: "Great Barrier",
  NZGR: "Great Mercury Island",
  NZGM: "Greymouth",
  NZHT: "Haast",
  NZHN: "Hamilton",
  NZHS: "Hastings",
  NZJH: "Hastings Hospital",
  NZHA: "Hawera",
  NZHB: "Helena Bay",
  NZHK: "Hokitika",
  NZNV: "Invercargill",
  NZKO: "Kaikohe",
  NZKI: "Kaikoura",
  NZKJ: "Kaikoura Beachfront",
  NZKF: "Kaipara Flats",
  NZKT: "Kaitaia",
  NZJK: "Kaitaia Hospital",
  NZKM: "Karamea",
  NZWE: "Kauaroa Bay",
  NZKH: "Kenepuru Hospital",
  NZKK: "Kerikeri/Bay of Islands",
  NZKP: "Koputaroa",
  NZKY: "Kowhai",
  NZKU: "Kupe",
  NZHP: "Lake Haupiri",
  NZLE: "Lake Station/Nelson Lakes",
  NZLA: "Loburn Abbey",
  NZMX: "Maari",
  NZMW: "Makarora",
  NZOG: "Makarora Heliport",
  NZVL: "Mandeville",
  NZMG: "Mangonui",
  NZSO: "Marlborough Sounds",
  NZMJ: "Martins Bay",
  NZMS: "Masterton",
  NZMA: "Matamata",
  NZUA: "Maui A",
  NZUB: "Maui B",
  NZMB: "Mechanics Bay",
  NZME: "Mercer",
  NZML: "Mid Waiho Loop",
  NZMF: "Milford Sound",
  NZMK: "Motueka",
  NZKD: "Motu Kaikoura Island",
  NZMC: "Mount Cook",
  NZMR: "Murchison",
  NZUR: "Murchison Hospital",
  NZNR: "Napier",
  NZNS: "Nelson",
  NZNH: "Nelson Hospital",
  NZNP: "New Plymouth",
  NZNF: "Norfolk",
  NZNE: "North Shore",
  NZJN: "North Shore Hospital",
  NZOU: "Oamaru",
  NZOR: "Oamaru Hospital",
  NZOB: "Ocean Beach",
  NZOH: "Ohakea (MIL)",
  NZOX: "Okiwi Station",
  NZOF: "Omaha Flats",
  NZOM: "Omaka",
  NZOA: "Omarama",
  NZOP: "Opotiki",
  NZOT: "Otaki",
  NZPA: "Paihia",
  NZPM: "Palmerston North",
  NZJM: "Palmerston North Hospital",
  NZPW: "Papawai",
  NZPI: "Parakai",
  NZPP: "Paraparaumu",
  NZUN: "Pauanui Beach",
  NZPN: "Picton",
  NZPK: "Pikes Point",
  NZPO: "Porangahau",
  NZPH: "Pudding Hill",
  NZUK: "Pukaki",
  NZPU: "Pukekohe",
  NZQN: "Queenstown",
  NZQW: "Queens Wharf",
  NZRA: "Raglan",
  NZRT: "Rangiora",
  NZRK: "Rangitaiki",
  NZRI: "Rangitata Island",
  NZJW: "Rawene Hospital",
  NZRO: "Rotorua",
  NZJO: "Rotorua Hospital",
  NZLF: "Rotorua Lakefront",
  NZRL: "Rotorua Lakes",
  NZRX: "Roxburgh",
  NZRW: "Ruawai",
  NZRC: "Ryans Creek",
  NZSH: "Skyline Helipad",
  NZJS: "Southland – Kew Hospital",
  NZSF: "Springfield",
  NZSL: "Springhill",
  NZSD: "Stratford",
  NZAH: "Taharoa Iron Sands",
  NZTI: "Taieri",
  NZVR: "Taihape",
  NZTK: "Takaka",
  NZJQ: "Taranaki Base Hospital",
  NZTM: "Taumarunui",
  NZJT: "Taumarunui Hospital",
  NZAP: "Taupo",
  NZJZ: "Taupo Hospital",
  NZLT: "Taupo Water",
  NZTG: "Tauranga",
  NZJA: "Tauranga Hospital",
  NZMO: "Te Anau/Manapouri",
  NZTL: "Tekapo",
  NZTP: "Tekapo/Mackenzie",
  NZTE: "Te Kowhai",
  NZTT: "Te Kuiti",
  NZTQ: "Te Kuiti Hospital",
  NZJP: "Te Puia Springs Hospital",
  NZTH: "Thames",
  NZJD: "Thames Hospital",
  NZTU: "Timaru",
  NZTO: "Tokoroa",
  NZJX: "Tokoroa Hospital",
  NZUI: "Tui",
  NZTN: "Turangi",
  NZKE: "Waiheke",
  NZWV: "Waihi Beach",
  NZHH: "Waikato Hospital",
  NZWM: "Waimate",
  NZYP: "Waipukurau",
  NZMH: "Wairarapa Hospital",
  NZJB: "Wairau Hospital",
  NZWO: "Wairoa",
  NZJY: "Wairoa Hospital",
  NZWF: "Wanaka",
  NZWN: "Wellington",
  NZWH: "Wellington Hospital",
  NZWJ: "Wellsford",
  NZWL: "West Melton",
  NZWS: "Westport",
  NZWK: "Whakatane",
  NZJF: "Whakatane Hospital",
  NZWG: "Whangamata",
  NZWU: "Whanganui",
  NZJU: "Whanganui Hospital",
  NZWR: "Whangarei",
  NZJR: "Whangarei Hospital",
  NZES: "Wharepapa South",
  NZWP: "Whenuapai (MIL)",
  NZWT: "Whitianga",
  NZWB: "Woodbourne",
  NZWY: "Wyndale"
};
